tankS3FileCreatedHandler:
  handler: handlers/s3/tankS3FileCreatedHandler.process
  timeout: 900
  tags:
    DEPARTMENT: MACHINERY
    ENVIRONMENT: DEV

  events:
    - existingS3:
        bucket: ${self:custom.tanksBucket}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .json
